@csrf
<div class="row g-3">
@foreach([
['business_name','Business Name',6],['customer_name','Customer Name',6],['email','Email',4],['phone','Phone',4],['alternate_phone','Alternate Phone',4],['gst_number','GST Number',4],['city','City',4],['state','State',4],['country','Country',4],['pincode','Pincode',4],['credit_limit','Credit Limit',4]
] as [$field,$label,$cols])
    <div class="col-md-{{ $cols }}"><label class="form-label" for="{{ $field }}">{{ $label }}</label><input class="form-control @error($field) is-invalid @enderror" id="{{ $field }}" name="{{ $field }}" value="{{ old($field, $customer->{$field}) }}" @if(in_array($field, ['business_name','customer_name','email','credit_limit'])) required @endif @if($field === 'email') type="email" @elseif($field === 'credit_limit') type="number" step="0.01" min="0" @endif>@error($field)<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
@endforeach
    <div class="col-md-4"><label class="form-label" for="business_type">Business Type</label><select class="form-select @error('business_type') is-invalid @enderror" id="business_type" name="business_type"><option value="">Select type</option>@foreach($businessTypes as $type)<option value="{{ $type }}" @selected(old('business_type', $customer->business_type) === $type)>{{ str($type)->headline() }}</option>@endforeach</select>@error('business_type')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="status">Status</label><select class="form-select @error('status') is-invalid @enderror" id="status" name="status" required>@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $customer->status ?? 'active') === $status)>{{ str($status)->headline() }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="billing_address">Billing Address</label><textarea class="form-control @error('billing_address') is-invalid @enderror" id="billing_address" name="billing_address" rows="4">{{ old('billing_address', $customer->billing_address) }}</textarea>@error('billing_address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="shipping_address">Shipping Address</label><textarea class="form-control @error('shipping_address') is-invalid @enderror" id="shipping_address" name="shipping_address" rows="4">{{ old('shipping_address', $customer->shipping_address) }}</textarea>@error('shipping_address')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="notes">Notes</label><textarea class="form-control @error('notes') is-invalid @enderror" id="notes" name="notes" rows="3">{{ old('notes', $customer->notes) }}</textarea>@error('notes')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div>
<div class="d-flex gap-2 mt-4"><button class="btn btn-primary" type="submit">Save Customer</button><a class="btn btn-outline-secondary" href="{{ route('admin.customers.index') }}">Cancel</a></div>
