<x-layouts.admin title="Customers | LapkingHub" page-title="Customer Management">
    <div class="card shadow-sm mb-4"><div class="card-body"><form class="row g-3" method="GET">
        <div class="col-md-4"><input class="form-control" name="search" value="{{ $filters['search'] ?? '' }}" placeholder="Search customers, email, phone, GST"></div>
        <div class="col-md-2"><select class="form-select" name="status"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ str($status)->headline() }}</option>@endforeach</select></div>
        <div class="col-md-2"><select class="form-select" name="business_type"><option value="">All types</option>@foreach($businessTypes as $type)<option value="{{ $type }}" @selected(($filters['business_type'] ?? '') === $type)>{{ str($type)->headline() }}</option>@endforeach</select></div>
        <div class="col-md-2"><select class="form-select" name="trashed"><option value="">Active</option><option value="with" @selected(($filters['trashed'] ?? '') === 'with')>With trashed</option><option value="only" @selected(($filters['trashed'] ?? '') === 'only')>Only trashed</option></select></div>
        <div class="col-md-2 d-grid"><button class="btn btn-outline-primary">Filter</button></div>
    </form></div></div>
    <div class="card shadow-sm"><div class="card-header d-flex justify-content-between align-items-center"><h5 class="mb-0">Customers</h5><a class="btn btn-primary" href="{{ route('admin.customers.create') }}">Add Customer</a></div>
        <div class="table-responsive"><table class="table align-middle mb-0"><thead><tr><th>Code</th><th>Business</th><th>Contact</th><th>Status</th><th>Credit</th><th>Orders</th><th class="text-end">Actions</th></tr></thead><tbody>
        @forelse($customers as $customer)<tr class="{{ $customer->trashed() ? 'table-warning' : '' }}"><td class="fw-semibold">{{ $customer->customer_code }}</td><td><div>{{ $customer->business_name }}</div><small class="text-secondary">{{ str($customer->business_type)->headline() }}</small></td><td><div>{{ $customer->customer_name }}</div><small class="text-secondary">{{ $customer->email }} · {{ $customer->phone ?: 'No phone' }}</small></td><td><span class="badge text-bg-{{ $customer->status === 'active' ? 'success' : ($customer->status === 'blocked' ? 'danger' : 'secondary') }}">{{ str($customer->status)->headline() }}</span></td><td>₹{{ number_format((float) $customer->available_credit, 2) }} / ₹{{ number_format((float) $customer->credit_limit, 2) }}</td><td>{{ $customer->orders_count }}</td><td class="text-end"><a class="btn btn-sm btn-outline-secondary" href="{{ route('admin.customers.show', $customer) }}">View</a>@if(! $customer->trashed()) <a class="btn btn-sm btn-outline-primary" href="{{ route('admin.customers.edit', $customer) }}">Edit</a><form class="d-inline" method="POST" action="{{ route('admin.customers.destroy', $customer) }}">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form>@else <form class="d-inline" method="POST" action="{{ route('admin.customers.restore', $customer) }}">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-success">Restore</button></form>@endif</td></tr>
        @empty<tr><td class="text-center text-secondary py-4" colspan="7">No customers found.</td></tr>@endforelse
        </tbody></table></div><div class="card-footer">{{ $customers->links() }}</div></div>
</x-layouts.admin>
