@csrf
<div class="row g-3">
    <div class="col-md-6"><label class="form-label" for="manufacturer_id">Manufacturer</label><select class="form-select @error('manufacturer_id') is-invalid @enderror" id="manufacturer_id" name="manufacturer_id" required><option value="">Select manufacturer</option>@foreach($manufacturers as $manufacturer)<option value="{{ $manufacturer->id }}" @selected(old('manufacturer_id', $laptopModel->manufacturer_id) === $manufacturer->id)>{{ $manufacturer->name }}</option>@endforeach</select>@error('manufacturer_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="series_id">Series</label><select class="form-select @error('series_id') is-invalid @enderror" id="series_id" name="series_id" required><option value="">Select series</option>@foreach($seriesOptions as $series)<option value="{{ $series->id }}" @selected(old('series_id', $laptopModel->series_id) === $series->id)>{{ $series->name }}</option>@endforeach</select>@error('series_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="model_name">Model Name</label><input class="form-control @error('model_name') is-invalid @enderror" id="model_name" name="model_name" value="{{ old('model_name', $laptopModel->model_name) }}" required>@error('model_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="model_number">Model Number</label><input class="form-control @error('model_number') is-invalid @enderror" id="model_number" name="model_number" value="{{ old('model_number', $laptopModel->model_number) }}">@error('model_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="slug">Slug</label><input class="form-control @error('slug') is-invalid @enderror" id="slug" name="slug" value="{{ old('slug', $laptopModel->slug) }}" placeholder="Auto-generated when empty">@error('slug')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="release_year">Release Year</label><input class="form-control @error('release_year') is-invalid @enderror" id="release_year" name="release_year" type="number" value="{{ old('release_year', $laptopModel->release_year) }}">@error('release_year')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-4"><label class="form-label" for="status">Status</label><select class="form-select @error('status') is-invalid @enderror" id="status" name="status" required>@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $laptopModel->status ?? 'active') === $status)>{{ ucfirst($status) }}</option>@endforeach</select>@error('status')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-md-6"><label class="form-label" for="seo_title">SEO Title</label><input class="form-control @error('seo_title') is-invalid @enderror" id="seo_title" name="seo_title" value="{{ old('seo_title', $laptopModel->seo_title) }}">@error('seo_title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="description">Description</label><textarea class="form-control @error('description') is-invalid @enderror" id="description" name="description" rows="4">{{ old('description', $laptopModel->description) }}</textarea>@error('description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
    <div class="col-12"><label class="form-label" for="seo_description">SEO Description</label><textarea class="form-control @error('seo_description') is-invalid @enderror" id="seo_description" name="seo_description" rows="3">{{ old('seo_description', $laptopModel->seo_description) }}</textarea>@error('seo_description')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
</div><div class="d-flex gap-2 mt-4"><button class="btn btn-primary" type="submit">Save Laptop Model</button><a class="btn btn-outline-secondary" href="{{ route('admin.laptop-models.index') }}">Cancel</a></div>
