@csrf
<div class="row g-3">
    <div class="col-md-4"><label class="form-label">SKU</label><input name="sku" class="form-control" value="{{ old('sku', $product->sku) }}" required></div>
    <div class="col-md-4"><label class="form-label">Product Name</label><input name="name" class="form-control" value="{{ old('name', $product->name) }}" required></div>
    <div class="col-md-4"><label class="form-label">Slug</label><input name="slug" class="form-control" value="{{ old('slug', $product->slug) }}"></div>
    <div class="col-md-6"><label class="form-label">Brand</label><select name="brand_id" class="form-select"><option value="">No brand</option>@foreach($brands as $brand)<option value="{{ $brand->id }}" @selected(old('brand_id', $product->brand_id)===$brand->id)>{{ $brand->name }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Category</label><select name="category_id" class="form-select" required><option value="">Select category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product->category_id)===$category->id)>{{ $category->name }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Condition</label><select name="condition" class="form-select">@foreach($conditions as $condition)<option value="{{ $condition }}" @selected(old('condition', $product->condition ?? 'new')===$condition)>{{ ucfirst($condition) }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Stock Status</label><select name="stock_status" class="form-select">@foreach($stockStatuses as $stockStatus)<option value="{{ $stockStatus }}" @selected(old('stock_status', $product->stock_status ?? 'in_stock')===$stockStatus)>{{ str($stockStatus)->replace('_',' ')->title() }}</option>@endforeach</select></div>
    <div class="col-md-4"><label class="form-label">Status</label><select name="status" class="form-select">@foreach($statuses as $status)<option value="{{ $status }}" @selected(old('status', $product->status ?? 'draft')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Short Description</label><textarea name="short_description" class="form-control" rows="3">{{ old('short_description', $product->short_description) }}</textarea></div>
    <div class="col-md-6"><label class="form-label">Full Description</label><textarea name="description" class="form-control" rows="3">{{ old('description', $product->description) }}</textarea></div>
    <div class="col-md-4"><label class="form-label">Warranty</label><input name="warranty" class="form-control" value="{{ old('warranty', $product->warranty) }}"></div>
    <div class="col-md-4"><label class="form-label">OEM Part Number</label><input name="oem_part_number" class="form-control" value="{{ old('oem_part_number', $product->oem_part_number) }}"></div>
    <div class="col-md-4"><label class="form-label">Alternate Part Numbers</label><input name="alternate_part_numbers[]" class="form-control" value="{{ old('alternate_part_numbers.0', $product->alternatePartNumbers->pluck('part_number')->implode(',')) }}" placeholder="Use comma after save if needed"></div>
    <div class="col-md-3"><label class="form-label">MRP</label><input name="mrp" type="number" step="0.01" class="form-control" value="{{ old('mrp', $product->mrp) }}"></div>
    <div class="col-md-3"><label class="form-label">Selling Price</label><input name="price" type="number" step="0.01" class="form-control" value="{{ old('price', $product->price) }}" required></div>
    <div class="col-md-3"><label class="form-label">Cost Price</label><input name="cost_price" type="number" step="0.01" class="form-control" value="{{ old('cost_price', $product->cost_price) }}"></div>
    <div class="col-md-3"><label class="form-label">GST Rate</label><input name="gst_rate" type="number" step="0.01" class="form-control" value="{{ old('gst_rate', $product->gst_rate ?? 0) }}" required></div>
    <div class="col-md-3"><label class="form-label">MOQ</label><input name="minimum_order_quantity" type="number" class="form-control" value="{{ old('minimum_order_quantity', $product->minimum_order_quantity ?? 1) }}" required></div>
    <div class="col-md-3"><label class="form-label">Weight</label><input name="weight" type="number" step="0.001" class="form-control" value="{{ old('weight', $product->weight) }}"></div>
    <div class="col-md-2"><label class="form-label">Length</label><input name="dimensions[length]" type="number" step="0.01" class="form-control" value="{{ old('dimensions.length', $product->dimensions['length'] ?? '') }}"></div>
    <div class="col-md-2"><label class="form-label">Width</label><input name="dimensions[width]" type="number" step="0.01" class="form-control" value="{{ old('dimensions.width', $product->dimensions['width'] ?? '') }}"></div>
    <div class="col-md-2"><label class="form-label">Height</label><input name="dimensions[height]" type="number" step="0.01" class="form-control" value="{{ old('dimensions.height', $product->dimensions['height'] ?? '') }}"></div>
    <div class="col-md-4"><label class="form-label">HSN Code</label><input name="hsn_code" class="form-control" value="{{ old('hsn_code', $product->hsn_code) }}"></div>
    <div class="col-md-8"><label class="form-label">Compatible Laptop Models</label><select name="laptop_model_ids[]" class="form-select" multiple>@foreach($laptopModels as $model)<option value="{{ $model->id }}" @selected(collect(old('laptop_model_ids', $product->laptopModels->pluck('id')->all()))->contains($model->id))>{{ $model->manufacturer?->name }} {{ $model->name }} {{ $model->model_number }}</option>@endforeach</select></div>
    <div class="col-md-6"><label class="form-label">Meta Title</label><input name="meta_title" class="form-control" value="{{ old('meta_title', $product->meta_title) }}"></div>
    <div class="col-md-6"><label class="form-label">Meta Keywords</label><input name="meta_keywords" class="form-control" value="{{ old('meta_keywords', $product->meta_keywords) }}"></div>
    <div class="col-12"><label class="form-label">Meta Description</label><textarea name="meta_description" class="form-control">{{ old('meta_description', $product->meta_description) }}</textarea></div>
    <div class="col-md-3 form-check ms-2"><input name="is_featured" value="1" class="form-check-input" type="checkbox" @checked(old('is_featured', $product->is_featured))><label class="form-check-label">Featured</label></div>
    <div class="col-md-3 form-check"><input name="is_trending" value="1" class="form-check-input" type="checkbox" @checked(old('is_trending', $product->is_trending))><label class="form-check-label">Trending</label></div>
</div>
<div class="mt-4"><button class="btn btn-primary">Save Product</button><a href="{{ route('admin.products.index') }}" class="btn btn-outline-secondary">Cancel</a></div>
